# Exported from Render on 2026-06-20T04:58:04Z
version: "1"
projects:
  - name: My project
    environments:
      - name: Production
        services:
          - type: web
            name: OAUTH2.0
            runtime: node
            repo: https://github.com/blackadi/OAUTH2.0
            plan: free
            envVars:
              - key: JWKS_URI
                sync: false
              - key: JWT_ISSUER
                sync: false
              - key: JWT_SELF_SIGNED_CERT_PEM
                sync: false
              - key: JWT_PRIVATE_KEY_PEM
                sync: false
              - key: JWT_PUBLIC_KEY_PEM
                sync: false
              - key: AUTH_USERS
                sync: false
              - key: LOGOUT_REDIRECT_URI
                sync: false
              - key: LOGOUT_CLIENT_ID
                sync: false
              - key: ALLOWED_ORIGINS
                sync: false
              - key: SESSION_SECRET
                sync: false
              - key: LOG_LEVEL
                sync: false
              - key: MORGAN_FORMAT
                sync: false
              - key: NODE_ENV
                sync: false
              - key: PORT
                sync: false
              - key: AUTHLETE_SERVICE_ID
                sync: false
              - key: AUTHLETE_BASE_URL
                sync: false
              - key: AUTHLETE_BEARER_TOKEN
                sync: false
            region: frankfurt
            buildCommand: npm install && npm run build
            startCommand: npm start
            autoDeployTrigger: commit
            rootDir: server

          - type: static_site
            name: client
            runtime: static
            repo: https://github.com/blackadi/OAUTH2.0
            buildCommand: npm install && npm run build
            staticPublishPath: dist
            pullRequestPreviewsEnabled: true
            routes:
              - source: /*
                destination: /index.html
                type: rewrite
            envVars:
              - key: VITE_API_BASE_URL
                value: https://oauth2-0-ekh2.onrender.com/
              - key: VITE_REDIRECT_URI
                sync: false
              - key: VITE_SCOPES
                value: openid profile email
            rootDir: client
            autoDeployTrigger: commit
